### ISSUE TITLE
Vue loader doesnt load auto load components , requires manual import as below

### ISSUE THREAD

**Issue by sercanatalik** [wotamann/vuetify-form-base#24]
import Vue from 'vue';
import Vuetify,{VTextField,VAutocomplete,VSelect,VCombobox,Touch} from 'vuetify/lib';

export default new Vuetify({
});

Vue.use(Vuetify,{ components: {
    VTextField,VAutocomplete,VSelect,VCombobox,Touch
  }});

**Comment by rsilvestre** [comment]
@wotamann i spend 2 hours to find how to fix this issue, can you add this in the documentation?

**Comment by wotamann** [comment]
Vue-Loader doesn't autoload components, because Vuetify-Form-Base use built in Vue
```html
<component is="my-component" />
```
and therefore Components must be [manually imported](https://vuetifyjs.com/en/customization/a-la-carte/).

I think it is a Vue/Vuetify Installation Problem. But to avoid lost hours I will give a hint into the documentation.
