### ISSUE TITLE
Unknown custom element errors

### ISSUE THREAD

**Issue by Zyles** [wotamann/vuetify-form-base#48]
Tried copy pasting the example and I get console errors:

```

[Vuetify] [UPGRADE] 'v-content' is deprecated, use 'v-main' instead.

found in

---> <VMain>
       <App> at src/App.vue
         <Root>

Unknown custom element: <v-row> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

```
  "dependencies": {
    "core-js": "^3.6.5",
    "vue": "^2.6.11",
    "vuetify": "^2.3.7",
    "vuetify-form-base": "^0.2.4"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.4.0",
    "@vue/cli-plugin-eslint": "~4.4.0",
    "@vue/cli-service": "~4.4.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "sass": "^1.19.0",
    "sass-loader": "^8.0.0",
    "vue-cli-plugin-vuetify": "~2.0.7",
    "vue-template-compiler": "^2.6.11",
    "vuetify-loader": "^1.3.0"
  },
```

main.js:
```
import Vue from 'vue'
import App from './App.vue'
import vuetify from './plugins/vuetify'

Vue.config.productionTip = false

new Vue({
  vuetify,
  render: h => h(App)
}).$mount('#app')
```

Vuetify does in fact work.

Installed using vue-cli 4.4.6 and `vue add vuetify`

Using a-la-carte.

**Comment by webdo** [comment]
See #2, the last comment explain how to fix this kind of issue, just replace "{ VLayout, VCheckbox, VSelect }" by the components you need.

**Comment by Zyles** [comment]
Installations instructions unclear. How do I know what components I need? I am not calling them, vuetify-form-base is calling them and needs them.

If there are dependencies that vuetify-form-base needs it would be better if your component would require them itself.

**Comment by webdo** [comment]
I am not the author of this component, just trying to help you :)
I do agree but i think it has just been made without a-la-carte in mind.
If you read the link i posted i talked about the way i did it too.

**Comment by wotamann** [comment]
Thanks @webdo for your explanation and suggestions.

vuetify-form-base uses intern dynamic components with `<component :is="my-component">` This dynamic components must be registered locally as described in [Dynamic Components](https://vuetifyjs.com/en/customization/a-la-carte/#markup-js-a-la-carte-destructuring).   

Installations instructions and vuetify-form-base  can not know which vuetify-components your application needs, because everyone declares the schema individually and according to his needs

One solution could be to do it without a-la-carte or take a look at mapping of components for local registration

Components Mapping :
A) First look for global registered components (custom components) 
`{ type:'mycustom', ...} ` map to  component 'mycustom'
this works since 0.2.4

B) Look if Schema-Type exists in `typeToComponent` in vFormBase.vue
`{ type:'text', ...} ` map to  component mycustom 'v-text-field' 
```
typeToComponent = {
    text: 'v-text-field',
    password: 'v-text-field',
    email: 'v-text-field',
    tel: 'v-text-field',
    url: 'v-text-field',
    search: 'v-text-field',
    number: 'v-text-field', 
    date: 'v-date-picker',   
    time: 'v-time-picker',
    color: 'v-color-picker',
    img: 'v-img',
    textarea: 'v-textarea',
    range: 'v-slider',
    file: 'v-file-input',
    switch: 'v-switch',
    checkbox: 'v-checkbox',
    
 }
```
C) Finally try to prepend schema-type with 'v-' in order to get a valid vuetify component 
`{ type:'slider', ...} ` map to  component mycustom 'v-slider'

**Comment by Mashiane** [comment]
The issue here is that with Vuetify 2.3.10, some component names were changed, for example v-content is now named v-main, this is a vuetify issue. If for example, this library has a hard coded v-content "internally", it should now be named "v-main"

I hope this brings in some clarity.

Ta!

**Comment by wotamann** [comment]
Hi and THX for your contribution. 

**v-content** is not hardcoded in vuetify-form-base. But I will update the documentation next time
