### ISSUE TITLE
Can't resolve 'v-mask' with v0.3.2

### ISSUE THREAD

**Issue by jorgv** [wotamann/vuetify-form-base#75]
Hello,

I am using nuxt ssr, and yesterday upgraded from v0.2.5 to  v0.3.2 and when building the project I had this issue:

![image](https://user-images.githubusercontent.com/32174909/99536587-dafb1800-29aa-11eb-8ddc-23f15c712cb5.png)

I went back to v0.2.5 and everything works fine, I am not sure if I have to install other new dependency.

thanks

**Comment by wotamann** [comment]
I think you have to install `v-mask` instead of vue-the-mask
See change.log

 0.3.2
  issue #71 - Fix BUG: Select|Combo|autocomplete dont display items in type 'array' -> fixed generating default key 

  **BREAKING: changed mask-directive from 'vue-the-mask' to 'v-mask'   - v-mask https://github.com/probil/v-mask** 
  
Refactor: removing 'schema.mask' as special case in vFormBase.vue not possible (doesn't work with v-textarea) 
  add custom-component example with external component

**Comment by jorgv** [comment]
Hi. yes I think should be that, thanks @wotamann, shouldn't this new library be added to the package.json
